export const players = [
  "Michael Jordan",
  "LeBron James",
  "Kareem Abdul-Jabbar",
  "Magic Johnson",
  "Bill Russell",
  "Wilt Chamberlain",
  "Larry Bird",
  "Kobe Bryant",
  "Shaquille O'Neal",
  "Tim Duncan",
  "Hakeem Olajuwon ",
  "Kevin Durant",
  "Stephen Curry",
  "Oscar Robertson",
  "Karl Malone",
  "Moses Malone",
  "Kevin Garnett",
  "Jerry West",
  "Dirk Nowitzki ",
  "Julius Erving",
  "Elgin Baylor",
  "Giannis Antetokounmpo ",
  "Dwyane Wade",
  "David Robinson",
  "Charles Barkley",
  "Isiah Thomas",
  "Scottie Pippen",
  "Chris Paul",
  "John Havlicek",
  "Allen Iverson",
  "Bob Pettit",
  "John Stockton",
  "Kawhi Leonard",
  "Steve Nash ",
  "Patrick Ewing",
  "Rick Barry",
  "Bob Cousy",
  "Jason Kidd",
  "James Harden",
  "Elvin Hayes",
  "Nikola Jokic ",
  "Gary Payton",
  "Dominique Wilkins",
  "George Gervin",
  "Clyde Drexler",
  "George Mikan",
  "Anthony Davis",
  "Russell Westbrook",
  "James Worthy",
  "Carmelo Anthony",
  "Paul Pierce",
  "Bob McAdoo",
  "Damian Lillard",
  "Reggie Miller",
  "Wes Unseld",
  "Kevin McHale",
  "Ray Allen",
  "Pau Gasol ",
  "Walt Frazier",
  "Robert Parish",
  "Willis Reed",
  "Dwight Howard",
  "Dolph Schayes",
  "Chris Bosh",
  "Dennis Rodman",
  "Nate Archibald",
  "Pete Maravich",
  "Dave Cowens",
  "Tony Parker ",
  "Vince Carter",
  "Alex English",
  "Paul Arizin",
  "Earl Monroe",
  "Bernard King",
  "Tracy McGrady",
  "Kyrie Irving",
  "Hal Greer",
];

const teamsList = [
  "Boston Celtics",
  "Brooklyn Nets",
  "New York Knicks",
  "Philadelphia 76ers",
  "Toronto Raptors",
  "Chicago Bulls",
  "Cleveland Cavaliers",
  "Detroit Pistons",
  "Indiana Pacers",
  "Milwaukee Bucks",
  "Atlanta Hawks",
  "Charlotte Hornets",
  "Miami Heat",
  "Orlando Magic",
  "Washington Wizards",
  "Denver Nuggets",
  "Minnesota Timberwolves",
  "Oklahoma City Thunder",
  "Portland Trail Blazers",
  "Utah Jazz",
  "Golden State Warriors",
  "LA Clippers",
  "Los Angeles Lakers",
  "Phoenix Suns",
  "Sacramento Kings",
  "Dallas Mavericks",
  "Houston Rockets",
  "Memphis Grizzlies",
  "New Orleans Pelicans",
  "San Antonio Spurs",
];

function randomPassword() {
  return (
    Math.random().toString(36).slice(2) +
    Math.random().toString(36).toUpperCase().slice(2)
  );
}

const teamObjs = teamsList.map(team => {
  return {
    id: randomPassword(),
    name: team,
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  };
});

// console.log(teamObjs);

const playerObjNBA = [
  {
    id: "5emw42o5ycn4RK9DRT2622",
    name: "Michael Jordan",
    current_team: "",
    old_teams: [],
  },
  {
    id: "o0ty31pcrphGTSKPBGO66O",
    name: "LeBron James",
    current_team: "",
    old_teams: [],
  },
  {
    id: "g112sne1qhqCHRZQ5JO3Z9",
    name: "Kareem Abdul-Jabbar",
    current_team: "",
    old_teams: [],
  },
  {
    id: "7ydblxdj3xP6KCBEUCRII",
    name: "Magic Johnson",
    current_team: "",
    old_teams: [],
  },
  {
    id: "wsouxc3selM40ZXJP9ZCP",
    name: "Bill Russell",
    current_team: "",
    old_teams: [],
  },
  {
    id: "jj0y166pzcJFAVWVSSBPP",
    name: "Wilt Chamberlain",
    current_team: "",
    old_teams: [],
  },
  {
    id: "073gz2p7ph57S9908EVSS3",
    name: "Larry Bird",
    current_team: "",
    old_teams: [],
  },
  {
    id: "vfzm1k5a43oCBL15DABPVG",
    name: "Kobe Bryant",
    current_team: "",
    old_teams: [],
  },
  {
    id: "f98nf2jcrqfPK3487DWTZE",
    name: "Shaquille O'Neal",
    current_team: "",
    old_teams: [],
  },
  {
    id: "sr3y9l4nkjXT1EACWRRG",
    name: "Tim Duncan",
    current_team: "",
    old_teams: [],
  },
  {
    id: "snv13fqzzu9JRZEIEW8IQ",
    name: "Hakeem Olajuwon ",
    current_team: "",
    old_teams: [],
  },
  {
    id: "98h8r1vqvkcKQI3P4EXIX",
    name: "Kevin Durant",
    current_team: "",
    old_teams: [],
  },
  {
    id: "oajsgaosfeMTBWA9JLE3C",
    name: "Stephen Curry",
    current_team: "",
    old_teams: [],
  },
  {
    id: "5cbud6rwkqbGH78OSMEHT",
    name: "Oscar Robertson",
    current_team: "",
    old_teams: [],
  },
  {
    id: "co3yptxrcyfCBENFNIB1N",
    name: "Karl Malone",
    current_team: "",
    old_teams: [],
  },
  {
    id: "z8kzpt8xjisJVDQPVUJ8A",
    name: "Moses Malone",
    current_team: "",
    old_teams: [],
  },
  {
    id: "xn31zvkoxsC1HTW97K397",
    name: "Kevin Garnett",
    current_team: "",
    old_teams: [],
  },
  {
    id: "y59w4ejw36P0LY9ITBPG",
    name: "Jerry West",
    current_team: "",
    old_teams: [],
  },
  {
    id: "hfx9pccg3o82AZXSX87FD",
    name: "Dirk Nowitzki ",
    current_team: "",
    old_teams: [],
  },
  {
    id: "ttucdooihrC0LOOVO8UK7",
    name: "Julius Erving",
    current_team: "",
    old_teams: [],
  },
  {
    id: "ribv8tw5flaBCT5BNA5EL9",
    name: "Elgin Baylor",
    current_team: "",
    old_teams: [],
  },
  {
    id: "eewjvzkuzzdT3LNPB4QV9",
    name: "Giannis Antetokounmpo ",
    current_team: "",
    old_teams: [],
  },
  {
    id: "9fekwh0fi52B95TGV8NNP",
    name: "Dwyane Wade",
    current_team: "",
    old_teams: [],
  },
  {
    id: "9g2eapvmoreJFRW1TCX9C",
    name: "David Robinson",
    current_team: "",
    old_teams: [],
  },
  {
    id: "4ip77e7lxo8U1KT5P3BDL",
    name: "Charles Barkley",
    current_team: "",
    old_teams: [],
  },
  {
    id: "x3j0okrk94H4PPLPWIV2B",
    name: "Isiah Thomas",
    current_team: "",
    old_teams: [],
  },
  {
    id: "jgbsiahas4aDLK5PVG0XIQ",
    name: "Scottie Pippen",
    current_team: "",
    old_teams: [],
  },
  {
    id: "e5pgyqtyyvdTO9JHBV3GE",
    name: "Chris Paul",
    current_team: "",
    old_teams: [],
  },
  {
    id: "t5cuywricvR3BATEB0OW9",
    name: "John Havlicek",
    current_team: "",
    old_teams: [],
  },
  {
    id: "ulhcfnhizvgHRO73VND245",
    name: "Allen Iverson",
    current_team: "",
    old_teams: [],
  },
  {
    id: "etch63bj0m4JMKX5H1797",
    name: "Bob Pettit",
    current_team: "",
    old_teams: [],
  },
  {
    id: "14cg5j4qvm3rSFGK2PMMYO",
    name: "John Stockton",
    current_team: "",
    old_teams: [],
  },
  {
    id: "fwl96dm4vwXFAWWYOEH0B",
    name: "Kawhi Leonard",
    current_team: "",
    old_teams: [],
  },
  {
    id: "7enriknlxgfJMWZL1B59Y",
    name: "Steve Nash ",
    current_team: "",
    old_teams: [],
  },
  {
    id: "uvf02g0db69H01Y36YX1YG",
    name: "Patrick Ewing",
    current_team: "",
    old_teams: [],
  },
  {
    id: "sbcjoyzr5l9Q8IXX3IE5",
    name: "Rick Barry",
    current_team: "",
    old_teams: [],
  },
  {
    id: "4nfgo6vb4pxKDT9TRH8FOA",
    name: "Bob Cousy",
    current_team: "",
    old_teams: [],
  },
  {
    id: "sh1q8kxd9xYJ41FG6KPTB",
    name: "Jason Kidd",
    current_team: "",
    old_teams: [],
  },
  {
    id: "329b0173jyy2P7FVOHJLPG",
    name: "James Harden",
    current_team: "",
    old_teams: [],
  },
  {
    id: "22zhtcyf592THI0L24MCAG",
    name: "Elvin Hayes",
    current_team: "",
    old_teams: [],
  },
  {
    id: "u05f3eqxqyeN0EC82EAGD",
    name: "Nikola Jokic ",
    current_team: "",
    old_teams: [],
  },
  {
    id: "93axgyz7638V3ZFAUPZ8M",
    name: "Gary Payton",
    current_team: "",
    old_teams: [],
  },
  {
    id: "9mtf75s4a5lL4H8SS5OYLE",
    name: "Dominique Wilkins",
    current_team: "",
    old_teams: [],
  },
  {
    id: "5r3bpi2umoqP8D3E3PMWSE",
    name: "George Gervin",
    current_team: "",
    old_teams: [],
  },
  {
    id: "ecsi09aeznaP4NGFP0OP4C",
    name: "Clyde Drexler",
    current_team: "",
    old_teams: [],
  },
  {
    id: "gbp6s6km0lkIOMEUD3B14L",
    name: "George Mikan",
    current_team: "",
    old_teams: [],
  },
  {
    id: "yo284ri9lvO8PT8YIFLM",
    name: "Anthony Davis",
    current_team: "",
    old_teams: [],
  },
  {
    id: "prujujhnbs9VE7G0BEGQB8",
    name: "Russell Westbrook",
    current_team: "",
    old_teams: [],
  },
  {
    id: "xgaj94c4gfO8EHXU9HATE",
    name: "James Worthy",
    current_team: "",
    old_teams: [],
  },
  {
    id: "gycelp68hav15QKKYPKJIR",
    name: "Carmelo Anthony",
    current_team: "",
    old_teams: [],
  },
  {
    id: "86g39cneprTB5L4KWPEM",
    name: "Paul Pierce",
    current_team: "",
    old_teams: [],
  },
  {
    id: "x46bmys5gpgFCKZLDD985T",
    name: "Bob McAdoo",
    current_team: "",
    old_teams: [],
  },
  {
    id: "g4eddl4g8yh16L4O3B3I0Z",
    name: "Damian Lillard",
    current_team: "",
    old_teams: [],
  },
  {
    id: "jyxra6okj6lQ43Y192C6NA",
    name: "Reggie Miller",
    current_team: "",
    old_teams: [],
  },
  {
    id: "42q63wxzqs54LOSWAE5EV9",
    name: "Wes Unseld",
    current_team: "",
    old_teams: [],
  },
  {
    id: "c0vcf6x48e846MQ9IDEQIB",
    name: "Kevin McHale",
    current_team: "",
    old_teams: [],
  },
  {
    id: "4utkmhwqommY9BDXLTA9NF",
    name: "Ray Allen",
    current_team: "",
    old_teams: [],
  },
  {
    id: "b28tun57n4fX7DFRVQBYQF",
    name: "Pau Gasol ",
    current_team: "",
    old_teams: [],
  },
  {
    id: "6a1fx4jot8q9JBNY63P6FS",
    name: "Walt Frazier",
    current_team: "",
    old_teams: [],
  },
  {
    id: "ttebynz8tw9KDXYS79TSL",
    name: "Robert Parish",
    current_team: "",
    old_teams: [],
  },
  {
    id: "lislcg6eo63B0HIUPGA8G",
    name: "Willis Reed",
    current_team: "",
    old_teams: [],
  },
  {
    id: "8bvq34lp2uiSRISMKUD7",
    name: "Dwight Howard",
    current_team: "",
    old_teams: [],
  },
  {
    id: "xptcvyfwknC1XK6MIRF27",
    name: "Dolph Schayes",
    current_team: "",
    old_teams: [],
  },
  {
    id: "6kq3cd7vcqq0A8OGQ3EYHUU",
    name: "Chris Bosh",
    current_team: "",
    old_teams: [],
  },
  {
    id: "0qytsjnqnusbTZLM0FQE1SH",
    name: "Dennis Rodman",
    current_team: "",
    old_teams: [],
  },
  {
    id: "7gul5wpd9vUYC7B36JVWO",
    name: "Nate Archibald",
    current_team: "",
    old_teams: [],
  },
  {
    id: "utxh1zie7aeBYITRSB3Q0C",
    name: "Pete Maravich",
    current_team: "",
    old_teams: [],
  },
  {
    id: "y2z6szaj5xnXJC4GEGNOX",
    name: "Dave Cowens",
    current_team: "",
    old_teams: [],
  },
  {
    id: "zi1xcbp566lSG5QT8H7YG",
    name: "Tony Parker ",
    current_team: "",
    old_teams: [],
  },
  {
    id: "wmduzul0443IM9X8RFISH",
    name: "Vince Carter",
    current_team: "",
    old_teams: [],
  },
  {
    id: "28mcfmcuilxE8ZYJZV74TQ",
    name: "Alex English",
    current_team: "",
    old_teams: [],
  },
  {
    id: "lsbf8vo012J5DIZ1P2YF",
    name: "Paul Arizin",
    current_team: "",
    old_teams: [],
  },
  {
    id: "rcrem6mv0qf5P6TEOJ2RY",
    name: "Earl Monroe",
    current_team: "",
    old_teams: [],
  },
  {
    id: "9cgnjqxttkb76NYD9ZI8RP",
    name: "Bernard King",
    current_team: "",
    old_teams: [],
  },
  {
    id: "tspaiypr9mIO0H6G81KV9",
    name: "Tracy McGrady",
    current_team: "",
    old_teams: [],
  },
  {
    id: "3tvi71n1wzdQAR4IWDJ6TQ",
    name: "Kyrie Irving",
    current_team: "",
    old_teams: [],
  },
  {
    id: "0w1a5nz46gu900XMW1VQMB",
    name: "Hal Greer",
    current_team: "",
    old_teams: [],
  },
];

const teamObjNBA = [
  {
    id: "pkoud2obggYBEBUPFC76I",
    name: "Boston Celtics",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "fl705fd579tRAY7H4JUX6Q",
    name: "Brooklyn Nets",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "uhpvno8f5xa0MQ5UE0BMYRK",
    name: "New York Knicks",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "rknstj32hjjMHEWF1MYFG8",
    name: "Philadelphia 76ers",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "e0zizwv2igmIFPW9YQXG1H",
    name: "Toronto Raptors",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "7agg7ej82cLU1F7KJ9CO",
    name: "Chicago Bulls",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "a1gfc6jb8xqTII1WDI9QAC",
    name: "Cleveland Cavaliers",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "rzj1sps13kmEABDOI4UXGV",
    name: "Detroit Pistons",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "4oxfmpmppaiABZB58QRHDE",
    name: "Indiana Pacers",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "2rgjh92szr114N8OE2Q9ES",
    name: "Milwaukee Bucks",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "97wk0vopvu9U56P675GJ1",
    name: "Atlanta Hawks",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "0aiea4j12ewpT0WS7219H99",
    name: "Charlotte Hornets",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "4pli3a1k7y6SS1M8S10G",
    name: "Miami Heat",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "hhxpwr3s40fT6WA0WBNWR",
    name: "Orlando Magic",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "59rv45w3trJ3VCD5D39TQ",
    name: "Washington Wizards",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "lnxuwle6aoDVAF4I1879",
    name: "Denver Nuggets",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "zcr1tihkbhd6ZT7T8104KS",
    name: "Minnesota Timberwolves",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "efd6i8tbza3UFH08E9ZZK",
    name: "Oklahoma City Thunder",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "dc4nugvngtjWHAUQ8N6BJA",
    name: "Portland Trail Blazers",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "0yok1mdz84rYAE6RISVAMF",
    name: "Utah Jazz",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "nfosibpup7eVMJVLG9C7ED",
    name: "Golden State Warriors",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "pbf4u6ipsxiH91C824JSQN",
    name: "LA Clippers",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "8mht1s16c3ARHOTDN79E",
    name: "Los Angeles Lakers",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "xdbiix9ae40APEKRKH9KJV",
    name: "Phoenix Suns",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "9a00ydfr81eS5KL2QF92E",
    name: "Sacramento Kings",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "5e88g33ar8jJJSWNBUCM3N",
    name: "Dallas Mavericks",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "3b4svx296v175JYT77FY2O",
    name: "Houston Rockets",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "8kxoectixpo6VDE8N3ZD6A",
    name: "Memphis Grizzlies",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "zbtgugmz4aoS0UTHEK8GG",
    name: "New Orleans Pelicans",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
  {
    id: "r91c7hr1lin25BP1A5CVDG",
    name: "San Antonio Spurs",
    current_players: [],
    old_players: [],
    conference: "",
    division: "",
  },
];

let teamsJson = JSON.stringify(teamObjNBA);
// console.log(teamObjNBA);
// console.log(teamsJson);
